#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AngleXplore.Droid.Resource", IsApplication=true)]

namespace AngleXplore.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int btnAngles = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int btnClear = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int btnDown = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int btnExit = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int btnStart = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int btnUp = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int etAngle = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int ivIntro = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int llCanvas = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int llIntroCanvas = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Inro = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ateneo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon_angles = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_big = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int mathplus_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pcieerd = 2130837509;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
